mutations_path: "demo/TCGA_UCEC_SNVs.tsv" # Path to mutations file (.maf or custom .tsv)
# maf_patient_column_name: "Tumor_Sample_Barcode" # Name of column with patient IDs in MAF file
# maf_cancer_column_name: # Name of column with cancer type in MAF file, if applicable (only required for MAF files with multiple cancer types)
expression_path: "data/TCGA_mean_expression.tsv" # Path to file with mean expression data for each gene. Only relevant when using this type of scaling in recurrence-based methods.
repl_timing_path: "data/replication_timing.bed" # Path to file with replication timing. Only relevant when using this type of scaling in recurrence-based methods.
test_regions_path: "data/cds_chr1-22.tsv" # Path to file with region definitions.

out_dir: "demo/output/" # Output directory. Trailing slash.
out_base_name: "SEISMIC_result" # Output file name will start with this.

reference_genome: "hg38" # Genome assembly for the mutations, test_regions, and mut_effects - either hg19 or hg38 (GRCh37 and GRCh38 are also valid)
seq_type: "WXS" # WXS/WGS for mutation data
sig_type: "cohort" # cohort for WXS, patient/cohort for WGS
cancer_type: "UCEC" # Name of cancer type

annotate_cds_effects: TRUE # If tested regions are CDSs, set TRUE to compute mutation effects (missense/nonsense/synonymous), in order to analyse only nonsynonymous, for instance. If FALSE, treats all mutations the same.
effects_to_keep: # Include mutations with these effects in analysis. Only used if annotate_cds_effects is TRUE. The effects in CDS regions are m/n/s (missense/nonsense/synonymous).
  - "m"
  - "n"

# WXS-specific scaling
# The scaling options have no impact when not running tests with recurrence, as the cohort mutational skew method ignores recurrence.
scale_exp_to_repl_reg: FALSE # TRUE/FALSE. Scale mutation expectations using replication timing data.
scale_exp_to_expr_reg: FALSE # TRUE/FALSE. Scale mutation expectations using expression data.
min_test_region_length_for_regression: 5000 # Minimum length of a gene to perform scaling with replication timing or expression data.
wxs_covered_regions_path: "data/cds_chr1-22.tsv" # Path to region definitions used for trinucleotide-based mutation modelling when the mutation data seq_type is WXS


# WGS-specific scaling
# The scaling options have no impact when not running tests with recurrence, as the cohort mutational skew method ignores recurrence.
scale_exp_with_silent_muts: FALSE # TRUE/FALSE. Scale mutation expectations based on the number of silent mutations and mutations around the analysed region.
silent_mut_flank_upstream: 10000 # Include this number of bases upstream for this scaling option.
silent_mut_flank_downstream: 10000 # Include this number of bases downstream for this scaling option.
min_silent_mutations: 10 # Require at least this number of silent mutations to perform scaling with silent mutations.

# Which tests to perform. The scaling methods above are only relevant when running recurrence-based methods (recurrence or combined)
test_cohort_skew_alone: TRUE # TRUE/FALSE. Run cohort mutational skew test. This is the main method in SEISMIC, described in the paper.
test_recurrence_alone: FALSE # TRUE/FALSE. Run test based on recurrence.
test_combined_model: FALSE # TRUE/FALSE. Run test that evaluates both recurrence and cohort mutational skew.

# Plotting
plotting_max_p: 0.001 # Plot all regions with a P value in the cohort mutational skew test lower than this. Set to 0 to disable.
# plot_region_list: # Manually chosen regions to generate plots for
#   - "NRAS"
#   - "TP53"
plot_region_list_only: FALSE # Set to TRUE to only plot without outputting results, and only for regions in plot_region_list

# Filtering test regions
remove_overlapping_test_regions: FALSE # TRUE/FALSE. Removes genes that overlap each other at all if set to TRUE.
min_mutations: 3 # Require mutations in at least this number of tumours in a gene to analyse it.

no_of_simulations: 10000 # Number of cohorts to simulate
cores: 1 # Number of threads to use. Set higher if there is enough RAM (approximately 5-10 GB used per thread)
