mutations_path: "demo/TCGA_UCEC_SNVs.tsv"
# maf_patient_column_name: "Tumor_Sample_Barcode"
# maf_cancer_column_name:
# expression_path: "data/TCGA_mean_expression.tsv"
# repl_timing_path: "data/replication_timing.bed"
test_regions_path: "data/gene_cds.tsv"

out_dir: "demo/output/"
out_base_name: "SEISMIC_demo_UCEC_WXS_result_"

reference_genome: "hg19"
seq_type: "WXS"
sig_type: "cohort"
cancer_type: "UCEC"

annotate_cds_effects: TRUE
effects_to_keep:
  - "m"
  - "n"

# WXS-specific
scale_exp_to_repl_reg: FALSE
scale_exp_to_expr_reg: FALSE
# min_test_region_length_for_regression: 5000
wxs_covered_regions_path: "data/cds_chr1-22.tsv"


# WGS-specific
# scale_exp_with_silent_muts: FALSE
# silent_mut_flank_upstream: 10000
# silent_mut_flank_downstream: 10000
# min_silent_mutations: 10

# Which tests to perform
# Turn scaling back on if we run the recurrence tests
test_recurrence_alone: FALSE
test_cohort_skew_alone: TRUE
test_combined_model: FALSE

# Filtering test regions
remove_overlapping_test_regions: FALSE
min_mutations: 3

no_of_simulations: 10000
cores: 1
