mut_effects_path: "data/gene_cds_tiled_mut_effect.tsv.gz"
mutations_path: "demo/TCGA_UCEC_SNVs.tsv"
# maf_patient_column_name: "Tumor_Sample_Barcode"
# maf_cancer_column_name:
trinuc_bgcount_path: "data/trinuc_bgfreq_gene_cds.tsv"
# expression_path: "data/TCGA_mean_expression.tsv"
# repl_timing_path: "data/replication_timing.bed"
test_regions_path: "data/gene_cds.tsv"
test_region_name: "gene"

out_dir: "demo/output/"
out_base_name: "SEISMIC_demo_UCEC_WXS_result_"

seq_type: "WXS"
sig_type: "cohort"
cancer_type: "UCEC"
effects_to_keep:
  - "m"
  - "n"

# WXS-specific
scale_exp_to_repl_reg: FALSE
scale_exp_to_expr_reg: FALSE
# min_test_region_length_for_regression: 5000


# WGS-specific
# scale_exp_with_silent_muts: FALSE
# silent_mut_flank_upstream: 10000
# silent_mut_flank_downstream: 10000
# min_silent_mutations: 10

# Which tests to perform
# Turn scaling back on if we run the recurrence tests
test_recurrence_alone: FALSE
test_cohort_distribution_alone: TRUE
test_combined_model: FALSE

# Filtering test regions
remove_overlapping_test_regions: FALSE
min_mutations: 3

no_of_simulations: 10000
cores: 1
